name: Build

on:
  push:
    branches: ['main']
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Extract Tag Version
        id: extract_tag
        run: |
          VERSION=${GITHUB_REF##*/}
          VERSION_NO_PREFIX=${VERSION#v}
          echo "VERSION=$VERSION_NO_PREFIX" >> $GITHUB_ENV

      - name: Display Extracted Version
        run: |
          echo "Extracted version is: ${{ env.VERSION }}"
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Builds the jar Gradle
        run: ./gradlew jar -Pversion=${{ env.VERSION }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/libs/*.jar

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}